# Netlify Configuration
[build]
  base = "frontend"
  publish = "frontend"
  command = ""

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
